title: jewelski
description: Notes on data engineering and other things.
github_username: jewelski
url: https://jewelski.github.io
permalink: /:title/
theme: null
plugins:
  - jekyll-sitemap
exclude: [README.md, Gemfile, Gemfile.lock]
defaults:
  - scope: { path: "" }
    values: { layout: default }
